# Generated by Django 5.2.17 on 2026-10-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='previous_interaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
